INSERT INTO `currencies` (`name`, `code`, `symbol`, `active`) VALUES
('US Dollar', 'USD', '$', 1),
('Pound Sterling', 'GBP', '&pound;', 1),
('Euro', 'EUR', '&#8364;', 1),
('Australian Dollar', 'AUD', '$', 1),
('Singapore', 'SGD', '&#36;', 1),
('Swedish Krona', 'SEK', 'kr', 1),
('Danish Krone', 'DKK', 'kr', 1),
('Mexican Peso', 'MXN', '$', 1),
('Brazilian Real', 'BRL', 'R$', 1),
( 'Malaysian Ringgit', 'MYR', 'RM', 1),
( 'Philippine Peso', 'PHP', 'P', 1),
( 'Swiss Franc', 'CHF', '&euro;', 1),
( 'India', 'INR', '?', 1),
( 'Argentine Peso', 'ARS', '$', 1),
( 'Canadian Dollar', 'CAD', '&#36;', 1),
( 'Chinese Yuan', 'CNY', '&#165;', 1),
( 'Czech Republic Koruna', 'CZK', 'K&#269;', 1),
( 'Hong Kong Dollar', 'HKD', '&#36;', 1),
( 'Hungarian Forint', 'HUF', 'Ft', 1 ),
( 'Indonesian Rupiah', 'IDR', 'Rp', 1),
( 'Israeli New Sheqel', 'ILS', '&#8362;', 1),
( 'Japanese Yen', 'JPY', '&#165;', 1),
( 'South Korean Won', 'KRW', '&#8361;', 0),
( 'Norwegian Krone', 'NOK', 'kr', 1),
( 'New Zealand Dollar', 'NZD', '&#36;', 1),
( 'Polish Zloty', 'PLN', 'z&#322;', 1),
( 'Russian Ruble', 'RUB', 'p', 1),
( 'Thai Baht', 'THB', '&#3647;', 1),
( 'Turkish Lira', 'TRY', '&#8378;', 1),
( 'New Taiwan Dollar', 'TWD', '&#36;', 1),
( 'Vietnamese Dong', 'VND', '&#8363;', 1),
( 'South African Rand', 'ZAR', 'R', 1),
( 'INR rupee', 'INR', '$', 1),
( 'Pula', 'BWP', 'bwp', 1);
