<?php

use App\Menu;
use Illuminate\Database\Seeder;

class MenuSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    //Order 1
        $order2 = 0;
        Menu::create([
                "url" => "javascript:void(0)",
                "name" => "Hotel Name",
                "i18n" => "Hotel Name",
                "class" => "",
                "icon" => "",
                "order1" => 1,
                "order2" => $order2,
                "order3" => 0,
                "order4" => 0,
            ]);
        $order2++;
        Menu::create([
            "url" => "dashboard",
            "name" => "Dashboard",
            "i18n" => "Dashboard",
            "slug" => "dashboard",
            "class" => "waves-effect waves-cyan",
            "icon" => "settings_input_svideo",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 0,
            "order4" => 0,
        ]);

        Menu::create([
            "url" => "calendar",
            "name" => "Calendar",
            "i18n" => "Calendar",
            "slug" => "calendar",
            "class" => "waves-effect waves-cyan",
            "icon" => "today",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 0,
            "order4" => 0,
        ]);

        //Developers
        Menu::create([
            "url" => "javascript:void(0)",
            "name" => "Tasks",
            "i18n" => "Tasks",
            "class" => "collapsible-header waves-effect waves-cyan",
            "icon" => "event_note",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 0,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "developers/task",
            "name" => "Task list",
            "i18n" => "Task list",
            "slug" => "task-list",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 1,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "developers/create-developer",
            "name" => "Create Developer",
            "i18n" => "Create Developer",
            "slug" => "create-developer",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 1,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "developers/create-category",
            "name" => "Create Category",
            "i18n" => "Create Category",
            "slug" => "create-category",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 2,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "developers/create-subcategory",
            "name" => "Create Sub Category",
            "i18n" => "Create Sub Category",
            "slug" => "create-subcategory",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 3,
            "order4" => 0,
        ]);
    //General
        $order2++;
        Menu::create([
            "url" => "javascript:void(0)",
            "name" => "General",
            "i18n" => "General",
            "class" => "collapsible-header waves-effect waves-cyan",
            "icon" => "settings",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 0,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "default-settings",
            "name" => "Default Settings",
            "i18n" => "Default Settings",
            "slug" => "default-settings",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 1,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "hotel-custom-settings",
            "name" => "Hotel Custom Settings",
            "i18n" => "Hotel Custom Settings",
            "slug" => "hotel-custom-settings",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 2,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "invoice-number-settings",
            "name" => "Invoice Number Settings",
            "i18n" => "Invoice Number Settings",
            "slug" => "invoice-number-settings",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 3,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "departments",
            "name" => "Departments",
            "i18n" => "Departments",
            "slug" => "departments",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 4,
            "order4" => 0,
        ]);   Menu::create([
            "url" => "currencies",
            "name" => "Currencies",
            "i18n" => "Currencies",
            "slug" => "currencies",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 5,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "languages",
            "name" => "Languages",
            "i18n" => "Languages",
            "slug" => "languages",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 6,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "reasons-cancellation",
            "name" => "Reasons for Cancellation",
            "i18n" => "Reasons for Cancellation",
            "slug" => "reasons-cancellation",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 7,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "reason-tax-exempt",
            "name" => "Reasons for Tax-Exempt",
            "i18n" => "Reasons for Tax-Exempt",
            "slug" => "reason-tax-exempt",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 8,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "special-discounts",
            "name" => "Special Discounts",
            "i18n" => "Special Discounts",
            "slug" => "special-discounts",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 9,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "announcements",
            "name" => "Announcements",
            "i18n" => "Announcements",
            "slug" => "announcements",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 10,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "account-attributes",
            "name" => "Account Attributes",
            "i18n" => "account-attributes",
            "slug" => "test",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 11,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "pay-modes",
            "name" => "Pay Modes",
            "i18n" => "Pay Modes",
            "slug" => "pay-modes",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 12,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "payment-types",
            "name" => "Pay Types",
            "i18n" => "Pay Types",
            "slug" => "payment-types",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 13,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "counters",
            "name" => "Counters",
            "i18n" => "Counters",
            "slug" => "counters",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 14,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "identification-types",
            "name" => "Identification Types",
            "i18n" => "Identification Types",
            "slug" => "identification-types",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 15,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "guest-type",
            "name" => "Guest Type",
            "i18n" => "Guest Type",
            "slug" => "guest-type",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 16,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "source-business",
            "name" => "Source of Business",
            "i18n" => "Source of Business",
            "slug" => "source-business",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 17,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "promo-code",
            "name" => "PromoCode/Un-lock Deal",
            "i18n" => "PromoCode/Un-lock Deal",
            "slug" => "promo-code",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 18,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "tag-list",
            "name" => "Custom Tag List",
            "i18n" => "Custom Tag List",
            "slug" => "tag-list",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 19,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "fields",
            "name" => "Custom Fields",
            "i18n" => "Custom Fields",
            "slug" => "fields",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 20,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "mode-arrival-departure",
            "name" => "Mode of Arrival/Departure",
            "i18n" => "Mode of Arrival/Departure",
            "slug" => "mode-arrival-departure",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 21,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "preferences",
            "name" => "Preferences",
            "i18n" => "Preferences",
            "slug" => "preferences",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 22,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "cancellation-policy",
            "name" => "Cancellation Policy",
            "i18n" => "Cancellation Policy",
            "slug" => "cancellation-policy",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 23,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "booking-policy",
            "name" => "Booking Policy",
            "i18n" => "Booking Policy",
            "slug" => "booking-policy",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 24,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "minimun-bookable-nights",
            "name" => "Frontdesk Minimum Bookable Nights",
            "i18n" => "Frontdesk Minimum Bookable Nights",
            "slug" => "minimun-bookable-nights",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 25,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "email-configuration",
            "name" => "Email Configuration",
            "i18n" => "Email Configuration",
            "slug" => "email-configuration",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 26,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "emails-settings",
            "name" => "Email Settings",
            "i18n" => "Email Settings",
            "slug" => "emails-settings",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 27,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "locator-email-settings",
            "name" => "CC Locator Email Settings",
            "i18n" => "CC Locator Email Settings",
            "slug" => "locator-email-settings",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 28,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "notes",
            "name" => "Notes",
            "i18n" => "Notes",
            "slug" => "notes",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 29,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "logged-user",
            "name" => "Logged In User(s)",
            "i18n" => "Logged In User(s)",
            "slug" => "logged-user",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" =>30 ,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "login-script",
            "name" => "Frontdesk Login Script",
            "i18n" => "Frontdesk Login Script",
            "slug" => "login-script",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 31,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "early-bird-discount",
            "name" => "Early Bird Discount",
            "i18n" => "early-bird-discount",
            "slug" => "test",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 32,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "last-minute-discount",
            "name" => "Last Minute Discount",
            "i18n" => "Last Minute Discount",
            "slug" => "last-minute-discount",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 33,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "long-stay-discount",
            "name" => "Long Stay Discount",
            "i18n" => "Long Stay Discount",
            "slug" => "long-stay-discount",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 34,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "dynamic-pricing",
            "name" => "Dynamic Pricing",
            "i18n" => "Dynamic Pricing",
            "slug" => "dynamic-pricing",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 35,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "market-segment",
            "name" => "Market Segment",
            "i18n" => "Market Segment",
            "slug" => "market-segment",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 36,
            "order4" => 0,
        ]);
    // Company Info
        $order2++;
        Menu::create([
            "url" => "javascript:void(0)",
            "name" => "Company Info",
            "i18n" => "Company Info",
            "class" => "collapsible-header waves-effect waves-cyan",
            "icon" => "hotel",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 0,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "company-profile",
            "name" => "Company Profile",
            "i18n" => "Company Profile",
            "slug" => "company-profile",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 1,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "hotel-information",
            "name" => "Hotel Information",
            "i18n" => "Hotel Information",
            "slug" => "hotel-information",
            "class" => "waves-effect waves-cyan",
            "icon" => "settings_input_svideo",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 2,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "hotel-manager",
            "name" => "Hotel Manager",
            "i18n" => "Hotel Manager",
            "slug" => "hotel-manager",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 3,
            "order4" => 0,
        ]);

        // End Company Info

    // Rooms Manager 3
        $order2++;
        Menu::create([
            "url" => "javascript:void(0)",
            "name" => "Rooms Manager",
            "i18n" => "Rooms Manager",
            "class" => "collapsible-header waves-effect waves-cyan",
            "icon" => "room",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 0,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "amenities",
            "name" => "Amenities",
            "i18n" => "Amenities",
            "slug" => "amenities",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 1,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "blocks",
            "name" => "Blocks",
            "i18n" => "Blocks",
            "slug" => "blocks",
            "class" => "waves-effect waves-cyan",
            "icon" => "settings_input_svideo",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 2,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "floors",
            "name" => "Floors",
            "i18n" => "Floorsr",
            "slug" => "floors",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 3,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "room-types",
            "name" => "Room Types",
            "i18n" => "Room Types",
            "slug" => "room-types",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 4,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "rooms",
            "name" => "Rooms",
            "i18n" => "Rooms",
            "slug" => "rooms",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 5,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "sort-rooms",
            "name" => "Sort Rooms",
            "i18n" => "Sort Rooms",
            "slug" => "sort-rooms",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 6,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "other-hotel-area",
            "name" => "Other Hotel Area",
            "i18n" => "Other Hotel Area",
            "slug" => "other-hotel-area",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 7,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "display-color",
            "name" => "Display Colors",
            "i18n" => "Display Colors",
            "slug" => "display-color",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 8,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "room-taxes",
            "name" => "Room Taxes",
            "i18n" => "Room Taxes",
            "slug" => "room-taxes",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 9,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "phone-extensions",
            "name" => "Phone Extensions",
            "i18n" => "Phone Extensions",
            "slug" => "phone-extensions",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 10,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "overbooking",
            "name" => "Overbooking",
            "i18n" => "Overbooking",
            "slug" => "overbooking",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 11,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "bill-message",
            "name" => "Bill Messages",
            "i18n" => "Bill Messages",
            "slug" => "bill-message",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 11,
            "order4" => 0,
        ]);

    //Price Manager
        $order2++;
        Menu::create([
            "url" => "javascript:void(0)",
            "name" => "Price Manager",
            "i18n" => "Price Manager",
            "class" => "collapsible-header waves-effect waves-cyan",
            "icon" => "attach_money",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 0,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "seasons-attribute",
            "name" => "Seasons Attribute",
            "i18n" => "Seasons Attribute",
            "slug" => "seasons-attribute",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 1,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "admin-season",
            "name" => "Seasons",
            "i18n" => "Seasons",
            "slug" => "admin-season",
            "class" => "waves-effect waves-cyan",
            "icon" => "settings_input_svideo",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 2,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "special-periods",
            "name" => "Special Periods",
            "i18n" => "Special Periods",
            "slug" => "special-periods",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 3,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "room-prices",
            "name" => "Room Prices",
            "i18n" => "Room Prices",
            "slug" => "room-prices",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 4,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "inclusions",
            "name" => "Add-ons (Inclusions)",
            "i18n" => "Add-ons (Inclusions)",
            "slug" => "inclusions",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 5,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "packages-master",
            "name" => "Packages Master",
            "i18n" => "Packages Master",
            "slug" => "packages-master",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 6,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "frontdesk-packages",
            "name" => "Frontdesk (Packages)",
            "i18n" => "Frontdesk (Packages)",
            "slug" => "frontdesk-packages",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 7,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "web-packages",
            "name" => "Web (Packages)",
            "i18n" => "Web (Packages)",
            "slug" => "web-packages",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 8,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "corporate-packages",
            "name" => "Corporate (Packages)",
            "i18n" => "Corporate (Packages)",
            "slug" => "corporate-packages",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 9,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "travelagent-packages",
            "name" => "Travel Agent (Packages)",
            "i18n" => "Travel Agent (Packages)",
            "slug" => "travelagent-packages",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 10,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "vipguest-packages",
            "name" => "VIP Guest (Packages)",
            "i18n" => "VIP Guest  (Packages)",
            "slug" => "vipguest-packages",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 11,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "other-packages",
            "name" => "Other (GDS Packages)",
            "i18n" => "Other (GDS Packages)",
            "slug" => "other-packages",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 12,
            "order4" => 0,
        ]);

        Menu::create([
            "url" => "display-color",
            "name" => "Display Colors",
            "i18n" => "Display Colors",
            "slug" => "display-color",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 13,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "centralized-rate",
            "name" => "Centralized Rate",
            "i18n" => "Centralized Rate",
            "slug" => "centralized-rate",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => 3,
            "order3" => 14,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "group-booking",
            "name" => "Group(Booking Source)",
            "i18n" => "Group(Booking Source)",
            "slug" => "group-booking",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 15,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "group-tax",
            "name" => "Group Tax",
            "i18n" => "Group Tax",
            "slug" => "group-tax",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 16,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "rate-manager",
            "name" => "Rate Manager",
            "i18n" => "Rate Manager",
            "slug" => "rate-manager",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 17,
            "order4" => 0,
        ]);

    //POS Manager
        $order2++;
        Menu::create([
            "url" => "javascript:void(0)",
            "name" => "POS Manager",
            "i18n" => "POS Manager",
            "class" => "collapsible-header waves-effect waves-cyan",
            "icon" => "store",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 0,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "pospoints",
            "name" => "POS Points",
            "i18n" => "POS Points",
            "slug" => "pospoints",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 1,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "postaxes",
            "name" => "POS Taxes",
            "i18n" => "POS Taxes",
            "slug" => "postaxes",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 2,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "measurement-units",
            "name" => "Measurement Units",
            "i18n" => "Measurement Units",
            "slug" => "measurement-units",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 3,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "posattribute",
            "name" => "Pos Attribute",
            "i18n" => "Pos Attribute",
            "slug" => "posattribute",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 4,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "positems",
            "name" => "POS Items",
            "i18n" => "POS Items",
            "slug" => "positems",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 5,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "productcategories",
            "name" => "Categories",
            "i18n" => "Categories",
            "slug" => "productcategories",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 6,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "products",
            "name" => "Products",
            "i18n" => "Products",
            "slug" => "products",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 7,
            "order4" => 0,
        ]);
        Menu::create([
            "url" => "posbillmessage",
            "name" => "Bill Messages",
            "i18n" => "Bill Messages",
            "slug" => "posbillmessage",
            "class" => "",
            "icon" => "",
            "order1" => 1,
            "order2" => $order2,
            "order3" => 8,
            "order4" => 0,
        ]);

    }

}

