INSERT INTO `time_zones` (`value`, `abbr`, `offset`, `isdst`, `text`, `utc`, `zone`) VALUES
('SA Western Standard Time', 'SWST', -4, 0, '(UTC-04:00) Georgetown, La Paz, Manaus, San Juan', 'America/Anguilla,America/Antigua,America/Aruba,America/Barbados,America/Blanc-Sablon,America/Boa_Vista,America/Curacao,America/Dominica,America/Grand_Turk,America/Grenada,America/Guadeloupe,America/Guyana,America/Kralendijk,America/La_Paz,America/Lower_Princes,America/Manaus,America/Marigot,America/Martinique,America/Montserrat,America/Port_of_Spain,America/Porto_Velho,America/Puerto_Rico,America/Santo_Domingo,America/St_Barthelemy,America/St_Kitts,America/St_Lucia,America/St_Thomas,America/St_Vincent,America/Tortola,Etc/GMT+4', '-04:00'),
('Dateline Standard Time', 'DST', -12, 0, '(UTC-12:00) International Date Line West', 'Etc/GMT+12', '-12:00'),
('UTC-11', 'U', -11, 0, '(UTC-11:00) Coordinated Universal Time-11', 'Etc/GMT+11,Pacific/Midway,Pacific/Niue,Pacific/Pago_Pago', '-11:00'),
('Hawaiian Standard Time', 'HST', -10, 0, '(UTC-10:00) Hawaii', 'Etc/GMT+10,Pacific/Honolulu,Pacific/Johnston,Pacific/Rarotonga,Pacific/Tahiti', '-10:00'),
('Alaskan Standard Time', 'AKDT', -8, 1, '(UTC-09:00) Alaska', 'America/Anchorage,America/Juneau,America/Nome,America/Sitka,America/Yakutat', '-09:00'),
('Pacific Standard Time (Mexico)', 'PDT', -7, 1, '(UTC-08:00) Baja California', 'America/Santa_Isabel', '-08:00'),
('Pacific Daylight Time', 'PDT', -7, 1, '(UTC-07:00) Pacific Time (US & Canada)', 'America/Dawson,America/Los_Angeles,America/Tijuana,America/Vancouver,America/Whitehorse', '-07:00'),
('Pacific Standard Time', 'PST', -8, 0, '(UTC-08:00) Pacific Time (US & Canada)', 'America/Dawson,America/Los_Angeles,America/Tijuana,America/Vancouver,America/Whitehorse,PST8PDT', '-08:00'),
('US Mountain Standard Time', 'UMST', -7, 0, '(UTC-07:00) Arizona', 'America/Creston,America/Dawson_Creek,America/Hermosillo,America/Phoenix,Etc/GMT+7', '-07:00'),
('Mountain Standard Time (Mexico)', 'MDT', -6, 1, '(UTC-07:00) Chihuahua, La Paz, Mazatlan', 'America/Chihuahua,America/Mazatlan', '-07:00'),
('Mountain Standard Time', 'MDT', -6, 1, '(UTC-07:00) Mountain Time (US & Canada)', 'America/Boise,America/Cambridge_Bay,America/Denver,America/Edmonton,America/Inuvik,America/Ojinaga,America/Yellowknife,MST7MDT', '-07:00'),
('Central America Standard Time', 'CAST', -6, 0, '(UTC-06:00) Central America', 'America/Belize,America/Costa_Rica,America/El_Salvador,America/Guatemala,America/Managua,America/Tegucigalpa,Etc/GMT+6,Pacific/Galapagos', '-06:00'),
('Central Standard Time', 'CDT', -5, 1, '(UTC-06:00) Central Time (US & Canada)', 'America/Chicago,America/Indiana/Knox,America/Indiana/Tell_City,America/Matamoros,America/Menominee,America/North_Dakota/Beulah,America/North_Dakota/Center,America/North_Dakota/New_Salem,America/Rainy_River,America/Rankin_Inlet,America/Resolute,America/Winnipeg,CST6CDT', '-06:00'),
('Central Standard Time (Mexico)', 'CDT', -5, 1, '(UTC-06:00) Guadalajara, Mexico City, Monterrey', 'America/Bahia_Banderas,America/Cancun,America/Merida,America/Mexico_City,America/Monterrey', '-06:00'),
('Canada Central Standard Time', 'CCST', -6, 0, '(UTC-06:00) Saskatchewan', 'America/Regina,America/Swift_Current', '-06:00'),
('SA Pacific Standard Time', 'SPST', -5, 0, '(UTC-05:00) Bogota, Lima, Quito', 'America/Bogota,America/Cayman,America/Coral_Harbour,America/Eirunepe,America/Guayaquil,America/Jamaica,America/Lima,America/Panama,America/Rio_Branco,Etc/GMT+5', '-05:00'),
('Eastern Standard Time', 'EDT', -4, 1, '(UTC-05:00) Eastern Time (US & Canada)', 'America/Detroit,America/Havana,America/Indiana/Petersburg,America/Indiana/Vincennes,America/Indiana/Winamac,America/Iqaluit,America/Kentucky/Monticello,America/Louisville,America/Montreal,America/Nassau,America/New_York,America/Nipigon,America/Pangnirtung,America/Port-au-Prince,America/Thunder_Bay,America/Toronto,EST5EDT', '-05:00'),
('US Eastern Standard Time', 'UEDT', -4, 1, '(UTC-05:00) Indiana (East)', 'America/Indiana/Marengo,America/Indiana/Vevay,America/Indianapolis', '-05:00'),
('Venezuela Standard Time', 'VST', -5, 0, '(UTC-04:30) Caracas', 'America/Caracas', '-04:30'),
('Paraguay Standard Time', 'PYT', -4, 0, '(UTC-04:00) Asuncion', 'America/Asuncion', '-04:00'),
('Atlantic Standard Time', 'ADT', -3, 1, '(UTC-04:00) Atlantic Time (Canada)', 'America/Glace_Bay,America/Goose_Bay,America/Halifax,America/Moncton,America/Thule,Atlantic/Bermuda', '-04:00'),
('Central Brazilian Standard Time', 'CBST', -4, 0, '(UTC-04:00) Cuiaba', 'America/Campo_Grande,America/Cuiaba', '-04:00'),
('Pacific SA Standard Time', 'PSST', -4, 0, '(UTC-04:00) Santiago', 'America/Santiago,Antarctica/Palmer', '-04:00'),
('Newfoundland Standard Time', 'NDT', -3, 1, '(UTC-03:30) Newfoundland', 'America/St_Johns', '-03:30'),
('E. South America Standard Time', 'ESAST', -3, 0, '(UTC-03:00) Brasilia', 'America/Sao_Paulo', '-03:00'),
('Argentina Standard Time', 'AST', -3, 0, '(UTC-03:00) Buenos Aires', 'America/Argentina/La_Rioja,America/Argentina/Rio_Gallegos,America/Argentina/Salta,America/Argentina/San_Juan,America/Argentina/San_Luis,America/Argentina/Tucuman,America/Argentina/Ushuaia,America/Buenos_Aires,America/Catamarca,America/Cordoba,America/Jujuy,America/Mendoza', '-03:00'),
('SA Eastern Standard Time', 'SEST', -3, 0, '(UTC-03:00) Cayenne, Fortaleza', 'America/Araguaina,America/Belem,America/Cayenne,America/Fortaleza,America/Maceio,America/Paramaribo,America/Recife,America/Santarem,Antarctica/Rothera,Atlantic/Stanley,Etc/GMT+3', '-03:00'),
('Greenland Standard Time', 'GDT', -3, 1, '(UTC-03:00) Greenland', 'America/Godthab', '-03:00'),
('Montevideo Standard Time', 'MST', -3, 0, '(UTC-03:00) Montevideo', 'America/Montevideo', '-03:00'),
('Bahia Standard Time', 'BST', -3, 0, '(UTC-03:00) Salvador', 'America/Bahia', '-03:00'),
('UTC-02', 'U', -2, 0, '(UTC-02:00) Coordinated Universal Time-02', 'America/Noronha,Atlantic/South_Georgia,Etc/GMT+2', '-02:00'),
('Mid-Atlantic Standard Time', 'MDT', -1, 1, '(UTC-02:00) Mid-Atlantic - Old', '', '-02:00'),
('Azores Standard Time', 'ADT', 0, 1, '(UTC-01:00) Azores', 'America/Scoresbysund,Atlantic/Azores', '-01:00'),
('Cape Verde Standard Time', 'CVST', -1, 0, '(UTC-01:00) Cape Verde Is.', 'Atlantic/Cape_Verde,Etc/GMT+1', '-01:00'),
('Morocco Standard Time', 'MDT', 1, 1, '(UTC) Casablanca', 'Africa/Casablanca,Africa/El_Aaiun', '+00:00'),
('UTC', 'UTC', 0, 0, '(UTC) Coordinated Universal Time', 'America/Danmarkshavn,Etc/GMT', '+00:00'),
('Greenwich Mean Time', 'GMT', 0, 0, '(UTC) Edinburgh, London', 'Europe/Isle_of_Man,Europe/Guernsey,Europe/Jersey,Europe/London', '+00:00'),
('British Summer Time', 'BST', 1, 1, '(UTC+01:00) Edinburgh, London', 'Europe/Isle_of_Man,Europe/Guernsey,Europe/Jersey,Europe/London', '+01:00'),
('GMT Standard Time', 'GDT', 1, 1, '(UTC) Dublin, Lisbon', 'Atlantic/Canary,Atlantic/Faeroe,Atlantic/Madeira,Europe/Dublin,Europe/Lisbon', '+00:00'),
('Greenwich Standard Time', 'GST', 0, 0, '(UTC) Monrovia, Reykjavik', 'Africa/Abidjan,Africa/Accra,Africa/Bamako,Africa/Banjul,Africa/Bissau,Africa/Conakry,Africa/Dakar,Africa/Freetown,Africa/Lome,Africa/Monrovia,Africa/Nouakchott,Africa/Ouagadougou,Africa/Sao_Tome,Atlantic/Reykjavik,Atlantic/St_Helena', '+00:00'),
('W. Europe Standard Time', 'WEDT', 2, 1, '(UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna', 'Arctic/Longyearbyen,Europe/Amsterdam,Europe/Andorra,Europe/Berlin,Europe/Busingen,Europe/Gibraltar,Europe/Luxembourg,Europe/Malta,Europe/Monaco,Europe/Oslo,Europe/Rome,Europe/San_Marino,Europe/Stockholm,Europe/Vaduz,Europe/Vatican,Europe/Vienna,Europe/Zurich', '+01:00'),
('Central Europe Standard Time', 'CEDT', 2, 1, '(UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague', 'Europe/Belgrade,Europe/Bratislava,Europe/Budapest,Europe/Ljubljana,Europe/Podgorica,Europe/Prague,Europe/Tirane', '+01:00'),
('Romance Standard Time', 'RDT', 2, 1, '(UTC+01:00) Brussels, Copenhagen, Madrid, Paris', 'Africa/Ceuta,Europe/Brussels,Europe/Copenhagen,Europe/Madrid,Europe/Paris', '+01:00'),
('Central European Standard Time', 'CEDT', 2, 1, '(UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb', 'Europe/Sarajevo,Europe/Skopje,Europe/Warsaw,Europe/Zagreb', '+01:00'),
('W. Central Africa Standard Time', 'WCAST', 1, 0, '(UTC+01:00) West Central Africa', 'Africa/Algiers,Africa/Bangui,Africa/Brazzaville,Africa/Douala,Africa/Kinshasa,Africa/Lagos,Africa/Libreville,Africa/Luanda,Africa/Malabo,Africa/Ndjamena,Africa/Niamey,Africa/Porto-Novo,Africa/Tunis,Etc/GMT-1', '+01:00'),
('Namibia Standard Time', 'NST', 1, 0, '(UTC+01:00) Windhoek', 'Africa/Windhoek', '+01:00'),
('GTB Standard Time', 'GDT', 3, 1, '(UTC+02:00) Athens, Bucharest', 'Asia/Nicosia,Europe/Athens,Europe/Bucharest,Europe/Chisinau', '+02:00'),
('Middle East Standard Time', 'MEDT', 3, 1, '(UTC+02:00) Beirut', 'Asia/Beirut', '+02:00'),
('Egypt Standard Time', 'EST', 2, 0, '(UTC+02:00) Cairo', 'Africa/Cairo', '+02:00'),
('Syria Standard Time', 'SDT', 3, 1, '(UTC+02:00) Damascus', 'Asia/Damascus', '+02:00'),
('E. Europe Standard Time', 'EEDT', 3, 1, '(UTC+02:00) E. Europe', 'Asia/Nicosia,Europe/Athens,Europe/Bucharest,Europe/Chisinau,Europe/Helsinki,Europe/Kiev,Europe/Mariehamn,Europe/Nicosia,Europe/Riga,Europe/Sofia,Europe/Tallinn,Europe/Uzhgorod,Europe/Vilnius,Europe/Zaporozhye', '+02:00'),
('South Africa Standard Time', 'SAST', 2, 0, '(UTC+02:00) Harare, Pretoria', 'Africa/Blantyre,Africa/Bujumbura,Africa/Gaborone,Africa/Harare,Africa/Johannesburg,Africa/Kigali,Africa/Lubumbashi,Africa/Lusaka,Africa/Maputo,Africa/Maseru,Africa/Mbabane,Etc/GMT-2', '+02:00'),
('FLE Standard Time', 'FDT', 3, 1, '(UTC+02:00) Helsinki, Kyiv, Riga, Sofia, Tallinn, Vilnius', 'Europe/Helsinki,Europe/Kiev,Europe/Mariehamn,Europe/Riga,Europe/Sofia,Europe/Tallinn,Europe/Uzhgorod,Europe/Vilnius,Europe/Zaporozhye', '+02:00'),
('Turkey Standard Time', 'TDT', 3, 0, '(UTC+03:00) Istanbul', 'Europe/Istanbul', '+03:00'),
('Israel Standard Time', 'JDT', 3, 1, '(UTC+02:00) Jerusalem', 'Asia/Jerusalem', '+02:00'),
('Libya Standard Time', 'LST', 2, 0, '(UTC+02:00) Tripoli', 'Africa/Tripoli', '+02:00'),
('Jordan Standard Time', 'JST', 3, 0, '(UTC+03:00) Amman', 'Asia/Amman', '+03:00'),
('Arabic Standard Time', 'AST', 3, 0, '(UTC+03:00) Baghdad', 'Asia/Baghdad', '+03:00'),
('Kaliningrad Standard Time', 'KST', 3, 0, '(UTC+03:00) Kaliningrad, Minsk', 'Europe/Kaliningrad,Europe/Minsk', '+03:00'),
('Arab Standard Time', 'AST', 3, 0, '(UTC+03:00) Kuwait, Riyadh', 'Asia/Aden,Asia/Bahrain,Asia/Kuwait,Asia/Qatar,Asia/Riyadh', '+03:00'),
('E. Africa Standard Time', 'EAST', 3, 0, '(UTC+03:00) Nairobi', 'Africa/Addis_Ababa,Africa/Asmera,Africa/Dar_es_Salaam,Africa/Djibouti,Africa/Juba,Africa/Kampala,Africa/Khartoum,Africa/Mogadishu,Africa/Nairobi,Antarctica/Syowa,Etc/GMT-3,Indian/Antananarivo,Indian/Comoro,Indian/Mayotte', '+03:00'),
('Moscow Standard Time', 'MSK', 3, 0, '(UTC+03:00) Moscow, St. Petersburg, Volgograd', 'Europe/Kirov,Europe/Moscow,Europe/Simferopol,Europe/Volgograd', '+03:00'),
('Samara Time', 'SAMT', 4, 0, '(UTC+04:00) Samara, Ulyanovsk, Saratov', 'Europe/Astrakhan,Europe/Samara,Europe/Ulyanovsk', '+04:00'),
('Iran Standard Time', 'IDT', 5, 1, '(UTC+03:30) Tehran', 'Asia/Tehran', '+03:30'),
('Arabian Standard Time', 'AST', 4, 0, '(UTC+04:00) Abu Dhabi, Muscat', 'Asia/Dubai,Asia/Muscat,Etc/GMT-4', '+04:00'),
('Azerbaijan Standard Time', 'ADT', 5, 1, '(UTC+04:00) Baku', 'Asia/Baku', '+04:00'),
('Mauritius Standard Time', 'MST', 4, 0, '(UTC+04:00) Port Louis', 'Indian/Mahe,Indian/Mauritius,Indian/Reunion', '+04:00'),
('Georgian Standard Time', 'GST', 4, 0, '(UTC+04:00) Tbilisi', 'Asia/Tbilisi', '+04:00'),
('Caucasus Standard Time', 'CST', 4, 0, '(UTC+04:00) Yerevan', 'Asia/Yerevan', '+04:00'),
('Afghanistan Standard Time', 'AST', 5, 0, '(UTC+04:30) Kabul', 'Asia/Kabul', '+04:30'),
('West Asia Standard Time', 'WAST', 5, 0, '(UTC+05:00) Ashgabat, Tashkent', 'Antarctica/Mawson,Asia/Aqtau,Asia/Aqtobe,Asia/Ashgabat,Asia/Dushanbe,Asia/Oral,Asia/Samarkand,Asia/Tashkent,Etc/GMT-5,Indian/Kerguelen,Indian/Maldives', '+05:00'),
('Yekaterinburg Time', 'YEKT', 5, 0, '(UTC+05:00) Yekaterinburg', 'Asia/Yekaterinburg', '+05:00'),
('Pakistan Standard Time', 'PKT', 5, 0, '(UTC+05:00) Islamabad, Karachi', 'Asia/Karachi', '+05:00'),
('India Standard Time', 'IST', 6, 0, '(UTC+05:30) Chennai, Kolkata, Mumbai, New Delhi', 'Asia/Kolkata', '+05:30'),
('Sri Lanka Standard Time', 'SLST', 6, 0, '(UTC+05:30) Sri Jayawardenepura', 'Asia/Colombo', '+05:30'),
('Nepal Standard Time', 'NST', 6, 0, '(UTC+05:45) Kathmandu', 'Asia/Kathmandu', '+05:45'),
('Central Asia Standard Time', 'CAST', 6, 0, '(UTC+06:00) Astana', 'Antarctica/Vostok,Asia/Almaty,Asia/Bishkek,Asia/Qyzylorda,Asia/Urumqi,Etc/GMT-6,Indian/Chagos', '+06:00'),
('Bangladesh Standard Time', 'BST', 6, 0, '(UTC+06:00) Dhaka', 'Asia/Dhaka,Asia/Thimphu', '+06:00'),
('Myanmar Standard Time', 'MST', 7, 0, '(UTC+06:30) Yangon (Rangoon)', 'Asia/Rangoon,Indian/Cocos', '+06:30'),
('SE Asia Standard Time', 'SAST', 7, 0, '(UTC+07:00) Bangkok, Hanoi, Jakarta', 'Antarctica/Davis,Asia/Bangkok,Asia/Hovd,Asia/Jakarta,Asia/Phnom_Penh,Asia/Pontianak,Asia/Saigon,Asia/Vientiane,Etc/GMT-7,Indian/Christmas', '+07:00'),
('N. Central Asia Standard Time', 'NCAST', 7, 0, '(UTC+07:00) Novosibirsk', 'Asia/Novokuznetsk,Asia/Novosibirsk,Asia/Omsk', '+07:00'),
('China Standard Time', 'CST', 8, 0, '(UTC+08:00) Beijing, Chongqing, Hong Kong, Urumqi', 'Asia/Hong_Kong,Asia/Macau,Asia/Shanghai', '+08:00'),
('North Asia Standard Time', 'NAST', 8, 0, '(UTC+08:00) Krasnoyarsk', 'Asia/Krasnoyarsk', '+08:00'),
('Singapore Standard Time', 'MPST', 8, 0, '(UTC+08:00) Kuala Lumpur, Singapore', 'Asia/Brunei,Asia/Kuala_Lumpur,Asia/Kuching,Asia/Makassar,Asia/Manila,Asia/Singapore,Etc/GMT-8', '+08:00'),
('W. Australia Standard Time', 'WAST', 8, 0, '(UTC+08:00) Perth', 'Antarctica/Casey,Australia/Perth', '+08:00'),
('Taipei Standard Time', 'TST', 8, 0, '(UTC+08:00) Taipei', 'Asia/Taipei', '+08:00'),
('Ulaanbaatar Standard Time', 'UST', 8, 0, '(UTC+08:00) Ulaanbaatar', 'Asia/Choibalsan,Asia/Ulaanbaatar', '+08:00'),
('North Asia East Standard Time', 'NAEST', 8, 0, '(UTC+08:00) Irkutsk', 'Asia/Irkutsk', '+08:00'),
('Japan Standard Time', 'JST', 9, 0, '(UTC+09:00) Osaka, Sapporo, Tokyo', 'Asia/Dili,Asia/Jayapura,Asia/Tokyo,Etc/GMT-9,Pacific/Palau', '+09:00'),
('Korea Standard Time', 'KST', 9, 0, '(UTC+09:00) Seoul', 'Asia/Pyongyang,Asia/Seoul', '+09:00'),
('Cen. Australia Standard Time', 'CAST', 10, 0, '(UTC+09:30) Adelaide', 'Australia/Adelaide,Australia/Broken_Hill', '+09:30'),
('AUS Central Standard Time', 'ACST', 10, 0, '(UTC+09:30) Darwin', 'Australia/Darwin', '+09:30'),
('E. Australia Standard Time', 'EAST', 10, 0, '(UTC+10:00) Brisbane', 'Australia/Brisbane,Australia/Lindeman', '+10:00'),
('AUS Eastern Standard Time', 'AEST', 10, 0, '(UTC+10:00) Canberra, Melbourne, Sydney', 'Australia/Melbourne,Australia/Sydney', '+10:00'),
('West Pacific Standard Time', 'WPST', 10, 0, '(UTC+10:00) Guam, Port Moresby', 'Antarctica/DumontDUrville,Etc/GMT-10,Pacific/Guam,Pacific/Port_Moresby,Pacific/Saipan,Pacific/Truk', '+10:00'),
('Tasmania Standard Time', 'TST', 10, 0, '(UTC+10:00) Hobart', 'Australia/Currie,Australia/Hobart', '+10:00'),
('Yakutsk Standard Time', 'YST', 9, 0, '(UTC+09:00) Yakutsk', 'Asia/Chita,Asia/Khandyga,Asia/Yakutsk', '+09:00'),
('Central Pacific Standard Time', 'CPST', 11, 0, '(UTC+11:00) Solomon Is., New Caledonia', 'Antarctica/Macquarie,Etc/GMT-11,Pacific/Efate,Pacific/Guadalcanal,Pacific/Kosrae,Pacific/Noumea,Pacific/Ponape', '+11:00'),
('Vladivostok Standard Time', 'VST', 11, 0, '(UTC+11:00) Vladivostok', 'Asia/Sakhalin,Asia/Ust-Nera,Asia/Vladivostok', '+11:00'),
( 'New Zealand Standard Time', 'NZST', 12, 0, '(UTC+12:00) Auckland, Wellington', 'Antarctica/McMurdo,Pacific/Auckland', '+12:00'),
( 'UTC+12', 'U', 12, 0, '(UTC+12:00) Coordinated Universal Time+12', 'Etc/GMT-12,Pacific/Funafuti,Pacific/Kwajalein,Pacific/Majuro,Pacific/Nauru,Pacific/Tarawa,Pacific/Wake,Pacific/Wallis', '+12:00'),
( 'Fiji Standard Time', 'FST', 12, 0, '(UTC+12:00) Fiji', 'Pacific/Fiji', '+12:00'),
( 'Magadan Standard Time', 'MST', 12, 0, '(UTC+12:00) Magadan', 'Asia/Anadyr,Asia/Kamchatka,Asia/Magadan,Asia/Srednekolymsk', '+12:00'),
( 'Kamchatka Standard Time', 'KDT', 13, 1, '(UTC+12:00) Petropavlovsk-Kamchatsky - Old', 'Asia/Kamchatka', '+12:00'),
( 'Tonga Standard Time', 'TST', 13, 0, '(UTC+13:00) Nuku`alofa', 'Etc/GMT-13,Pacific/Enderbury,Pacific/Fakaofo,Pacific/Tongatapu', '+13:00'),
( 'Samoa Standard Time', 'SST', 13, 0, '(UTC+13:00) Samoa', 'Pacific/Apia', '+13:00');
